Java05. ДЗ 01, Макеев Владимир
mkvdv/au-java1-spring-2017 pull request #1
Opened 2018-03-03 13:05 UTC by mkvdv

@dsavvinov
Код задания в TrieImpl.java

2018-03-06 19:34 UTC, dsavvinov requested changes
В целом неплохо. Основная претензия -- не очень аккуратно написанный код в методах.

Учитывая скорость сдачи, готов 9б поставить сразу, или можешь попробовать исправить замечания, и я посмотрю еще раз.

2018-03-06 19:34 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/trie/TrieImpl.java
> +        while (ix < element.length()) {
Это можно как-нибудь упростить:
- Или использовать for-each, чтобы не таскать за собой индексы: `for (char currentChar : element.toCharArray())`, потому что индексы это отстой :)
- Или оставить `while`, но втащить условие `cur.getNote(...) != null` в условие цикла, потому что это в точности передает сколько этот цикл будет работать, и так легче читать

2018-03-06 19:34 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/trie/TrieImpl.java
> +        while (ix < element.length()) {
NPE, если переданный `element == null`. Это не очень хорошо, что NPE летит откуда-то из кишок программы: если `null` не поддерживается, то нужно сразу это проверят и кидаться исключениями в начале метода и с нормальными сообщениями.

2018-03-06 19:34 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/trie/TrieImpl.java
> +                    break;
Кажется, здесь можно сразу сделать `return`, тогда в строке 108 не придется какое-то довольное невразумительное условие вкорячивать

2018-03-06 19:34 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/trie/TrieImpl.java
> +    private Vertex root;
`final`

2018-03-06 19:34 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/trie/TrieImpl.java
> +        private Vertex upperNext[]; // for uppercase letters
По факту, эти два поля -- это такой `Map<Character, Vertex>`, но соптимизированный поскольку мы знаем что-то особое про input'ы. Т.е. для самого класса `Vertex` это деталь имплементации, а вообще говоря он хочет пользоваться Map-подобным API: `getNext(Character)`, `setNext(Chatacter, Vertex)`. Поэтому теоретически эту логику можно было бы вынести в отдельный класс (`TransitionsTable`, или как-то так), и спрятать детали про upperCase/lowerCase внутри него. 

Не настаиваю на этом рефакторинге, т.к. в данном случае отдельный класс для таблицы переходов похож на overengineering, так что это просто информация к сведению :)

2018-03-06 19:34 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/trie/TrieImpl.java
> +        void setNode(char c, Vertex vertex) {
Minor: возможно, лучше назвать это `setNext`.

2018-03-06 19:34 UTC, dsavvinov commented on src/test/java/ru/spbau/mit/java1/trie/TrieImplTest.java
> +            Assert.assertEquals(true, t.contains(small));
Minor. Здесь и далее: в тестах удобно делать `import static org.junit.Assert.assertEquals`, или даже `import static org.junit.Assert.*`, чтобы не замусоривать код постянным `Assert.*`

2018-03-06 19:34 UTC, dsavvinov commented on src/test/java/ru/spbau/mit/java1/trie/TrieImplTest.java
> +            Assert.assertEquals(true, t.contains(small));
Minor. Лучше последовать совету идеи и заменить это на `assertTrue(t.contains(small))`, так чуть легче читается код :)

2018-03-06 19:34 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/trie/TrieImpl.java
> +    }
В целом, этот и другие методы получились довольно мутные и тяжелые для чтения. Все это из-за того, что с первого взгляда тяжело понять control-flow в нем, и, как следствие, инварианты, которые выполняются в ключевых точках: после в начале итерации каждого из циклов, после первого цикла, после второго цикла, и т.п.

Если не очень понятно, что делать-то, то я на паре скажу пару слов про это.

2018-03-08 22:26 UTC, mkvdv commented on src/main/java/ru/spbau/mit/java1/trie/TrieImpl.java
> +                    break;
Не, его нельзя убирать (в текущей реализации).
Пусть мы из бора, содержащего строки `{"abc", "abcd"}` удаляем `"abc"`.
Тогда мы должны в узле `'c'` сделать пометку, что теперь тут не заканчивается слово.
Возможно, можно сделать без пометок `isEndOfWord`, не я не придумал, как.

2018-03-08 22:45 UTC, mkvdv commented
@dsavvinov
Исправил замечания, оставил везде по одному циклу, заменил на foreach.
Посмотрите, пожалуйста.

2018-03-11 17:01 UTC, dsavvinov approved these changes
Остались минорные помарки/замечания. Принято, 9.5б

2018-03-11 17:01 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/trie/TrieImpl.java
> +            throw new IncorrectInputException("element argument is null");
На самом деле, это не очень хорошая идея -- кидать тут checked exception. Вполне достаточно было просто кидать `NullPointerException`/`IllegalArgumentException`. Основное соображение, почему checked тут плохо -- потому что сложно вообразить себе такую ситуацию, когда клиенты этого API захотят поймать это исключение и что-нибудь осмысленное с ним сделать .

2018-03-11 17:01 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/trie/TrieImpl.java
> +        void setNext(char c, Vertex vertex) throws IncorrectInputException {
Ditto: checked exception не очень красиво тут смотрится
К примеру, в стандартной библиотеке Java в аналогичной по смыслу ситуации кидаются unchecked-exception'ом: https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#parseInt(java.lang.String)

2018-03-11 17:01 UTC, dsavvinov commented on src/test/java/ru/spbau/mit/java1/trie/TrieImplTest.java
> +            fail();
FYI, тело тестового метода не обязательно оборачивать в try-catch: можно смело добавлять в сигнатуру `throws Exception`, а параметр аннотации `@Test` проверит, что тест завершился именно так, как надо.

2018-03-11 17:23 UTC, mkvdv commented on src/test/java/ru/spbau/mit/java1/trie/TrieImplTest.java
> +            fail();
Да, действительно, удобно. 
Спасибо за замечания.

2018-04-19 10:18 UTC, closed without merging