Java05. ДЗ 02, Макеев Владимир
mkvdv/au-java1-spring-2017 pull request #2
Opened 2018-03-22 17:30 UTC by mkvdv

@dsavvinov
Код задания в DictionaryImpl.java

2018-03-28 10:39 UTC, dsavvinov requested changes
Неплохо.
В первую очередь, хочется, чтобы из кода исчез snake_case :) 
Еще с remove и индексами что-то не чисто.

И еще хочу услышать некоторый философский анализ того, как будет работать хэш-таблица в такой имплементации -- какие сценарии благоприятны для нее, какие нет, когда может случиться деградация производительности (представь например, что я твой коллега, и мне нужно заиспользовать хэш-таблицу, и я вот пришел к тебе и спрашиваю, могу ли я взять твою :) )

2018-03-28 10:39 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +        if (maxChainLength < 0) {
:+1:

2018-03-28 10:39 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +        int list_ix = myHash(key);
Здесь и далее: давайте уже избавляться от snake_case.

2018-03-28 10:39 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +        int stringIx = find_key(table.get(listIx), key);
Minor. "Индекс строчки" -- не совсем понятное название, т.к. не понятно где этот индекс. `indexInBucket` было бы понятнее (или `indexInList`, в терминологии данной работы)

2018-03-28 10:39 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +            chain.remove(string_ix);
Непонятно, почему после рехэширования данный ключ обязан сохранить свой индекс в цепочке.

2018-03-28 10:39 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +    private int find_key(LinkedList<Node> chain, String key) {
Любопытный факт: комментарий можно перенести в название функции, тогда он будет не нужен, а код читать станет легче, т.к. семантика функции будет ясна в любом месте её использования, а не только в месте, где она объявлена:
```
private int getKeyIndexInChain(chain, key)
```

2018-03-28 10:39 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +    private static final double MIN_FILL_FACTOR = 0.05; // пусть заполнена не менее чем на 5%
Из каких соображений выбиралась константа?

2018-03-28 10:39 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +            if (chain.size() < maxChainLength && size < maxSize) {
Из каких соображений выбиралось именно такое условие? Какие corner-case в работе хэш-таблицы с такой имплементацией могут возникать?

2018-04-06 14:41 UTC, mkvdv commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +            chain.remove(string_ix);
Исправл, добавил тесты, спасибо за замечание.

2018-04-06 14:51 UTC, mkvdv commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +    private static final double MIN_FILL_FACTOR = 0.05; // пусть заполнена не менее чем на 5%
Поменял на `0.25`, более популярная мультипликативная схема: при `resize` число элементов из `size/4` станет `size/2` и до следующего `resize` должно произойти либо `size/4` удалений, либо `size/2` добавлений. Амортизационно все операции за O(1).

2018-04-06 16:30 UTC, mkvdv commented
Добрый день!
Snake_case убрал, исправил remove и min_fill_factor взял другой.

По поводу вариантов использования: не уверен, что текущая реализация хеш-функции в хеш-таблице даст хорошее распределения по бакетам, я бы рекомендовал выбирать хеш функцию исходя из предполагаемых входных данных. 
При плохой хеш-функции из-за того, что мы берем остаток по модулю степени двойки, будут коллизии, нарастание цепочек и rehash. А так, если данные редко вставляются или удаляются, то поиск будет работать быстро, так как длина цепочек ограничена, а остаток по модулю 2^i процессор умеет делать сильно быстрее (зануление старших битиков), чем остаток от простого числа.

2018-04-17 18:12 UTC, dsavvinov approved these changes
Я, к сожалению, не понял принцип работы таблицы, поэтому прошу ответить на вопросы еще раз.

2018-04-17 18:12 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +        return key.hashCode() % maxSize;
Если `key.hashCode() < 0`, то где-нибудь что-нибудь взорвется.

2018-04-17 18:12 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +                rehash(size * 2); // increase size
Объясни мне, пожалуйста, как это работает, я не понимаю. 

`size` это, с одной стороны, количество элементов в хэш-таблице.
С другой стороны, мы передаем в `rehash` помноженный или поделенный `size`. Внутри rehash это число будет использоваться для создания бакетов. 

Т.е. такое ощущение, что при переполнении таблицы из n элементов, в ней будет создано n * 2 бакетов. Чего, конечно, хватит, но это как-то слишком уж щедро.

2018-04-17 23:51 UTC, mkvdv commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +                rehash(size * 2); // increase size
Да, всё так, при достижении `size` размера `maxSize` мы увеличиваем `maxSize` на `2` и делаем рехеширование. После этого таблица заполнена на половину.

При достижении `size` величины `0.25 * maxSize` мы уменьшаем `maxSize` в 2 раза и опять рехеширование. Таблица снова заполнена на половину.

Предполагалось использовать другую схему рехеширования?

2018-04-17 23:58 UTC, mkvdv commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +        return key.hashCode() % maxSize;
Поправил.

2018-04-18 00:09 UTC, mkvdv commented
@dsavvinov 
Исправил ошибку, подробнее описал схему расширения / сжатия таблицы.

2018-04-18 07:07 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +                rehash(size * 2); // increase size
> После этого таблица заполнена на половину
Если точнее, в ней бакетов в два раза больше, чем элементов. Мне кажется, это довольно расточительно -- обычно увеличивают количество **бакетов** в два раза (т.е. в терминах данной работы `rehash (table.size() * 2)`)

Я вроде понял задумку позади этого -- стараемся поддерживать инвариант "в одном бакете в среднем один элемент", верно?

2018-04-18 08:51 UTC, mkvdv commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +                rehash(size * 2); // increase size
>  обычно увеличивают количество бакетов в два раза

По сути, у меня это и происходит при достижении переменной `size` значения `maxSize` , ибо `maxSize` - это и есть число бакетов. Возможно, его логичнее переименовать в `numberOfBuckets`. При rehash это число изменяется.


> инвариант "в одном бакете в среднем один элемент"

В одном бакете не более `maxChainLength` элементов (задается в конструкторе). А число элементов во всей хеш-таблице не больше, чем число бакетов, и не меньше, чем 0.25 * число бакетов. Если хоть одно из условий нарушается - делается rehash. 

При этом число бакетов всегда не меньше, чем `DEFAULT_MAX_SIZE == 64`, чтобы на малом числе элементов много раз не делать `rehash`.

2018-04-18 09:08 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +                rehash(size * 2); // increase size
> По сути, у меня это и происходит при достижении переменной size значения maxSize , ибо maxSize - это и есть число бакетов.

Прости пожалуйста, я что-то опять перестал понимать. Я сейчас перескажу, как понимаю принцип работы, а ты поправь, если я где-то что-то напутал.

У нас есть два случая, когда производится рехэш -- если цепочка стала слишком длинной, или если элементов в таблице стало слишком много. Рассмотрим их по отдельности:

1. Текущая цепочка стала слишком длинной. Представим, что `size = 100`, `maxSize = 1000`, но так получилось, что очень много хэш-коллизий, и одна из цепочек переполнилась. Кажется, что тут мы выполним `rehash(size * 2)`, то есть `rehash(200)`, то есть **сожмемся**. 

2. Элементов в таблице стало слишком много. Вот тыт тут говоришь: 

> число элементов во всей хеш-таблице не больше, чем число бакетов

Т.е. условно 101 элемент в 100 бакетов не поместится даже при равномерном распределении хэшей, и для 101ого элемента будет ресайзится до 200 бакетов. Можешь, пожалуйста, пояснить, откуда такая логика взялась (может, это какой-то известный подход, о котором я просто не знаю)?

2018-04-18 10:54 UTC, mkvdv commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +                rehash(size * 2); // increase size
> то есть сожмемся.

Да, тут действительно ошибка, спасибо, переименовал `maxSize` в `numberOfBuckets`, ибо сам запутался. Предполагалось, что будет вызвано `rehash(numberOfBuckets * 2)`. Исправил.

> Т.е. условно 101 элемент в 100 бакетов не поместится даже при равномерном распределении хэшей, и для 101ого элемента будет ресайзится до 200 бакетов. 

Как мне казалось, если в таблице число элементов достигает числа бакетов, то по Дирихле неизбежны коллизии - а это сразу увеличивает время работы `get` и `put`, чего нам очень не хотелось бы, и мы делаем `bucketSize * 2` и какое-то время живем хорошо. Аналогично если нам дают плохие данные и у нас появилась длинная цепочка. 
Я отталкивался от того, что мы хотим быстрый `get` и `put` и у нас много памяти (а раз мы пишем на Java, то, скорее всего, у нас хватает памяти).

А бывают какие-то другие популярные схемы рехеширования при использовании цепочек? 
Я видел либо такие, либо увеличение в k раз при достижении `size` величины `maxLoadFactor * numberOfBuckets`, и параметры `k` и `maxLoadFactor` задаются при конструировании, и не очень очевидно, как их именно подбирать.

2018-04-18 11:28 UTC, dsavvinov commented on src/main/java/ru/spbau/mit/java1/dict/DictionaryImpl.java
> +                rehash(size * 2); // increase size
Ну, понятно, что любая стратегия более-менее сводится к проверке условия `size / numberOfBuckets < maxLoadFactor`, где `maxLoadFactor` некоторое число >= 1. Чем оно ближе к 1, тем быстрее (в среднем) работает `get` / `put`, но это покупается за счет памяти. Если больше `factor`, тем компактнее таблица, но тем длиннее могут возникать цепочки.

`maxLoadFactor = 1`, как в твоей работе, это довольно экстремальное значение. Возможно, стоило бы взять чуть больше (3-4) -- но по-хорошему это должно сопровождаться некоторыми экспериментальными измерениями, чего в данной работе я, конечно, не требую.

А вот что точно хорошо было бы сделать, так это предоставить пользователям возможность самим выбирать баланс между памятью/скоростью, посредством конструктора, принимающего этот коэффициент.

2018-04-18 11:29 UTC, dsavvinov approved these changes
В целом-то код хороший, и ответы на вопросы неплохие, но что-то довольно серьезных багов много наловили (аж три штуки -- с индексами при рехэше, с отрицательным хэшкодом, с ресайзом не в ту сторону). Повнимательнее :)

Принято, 7.5б

2018-04-19 10:19 UTC, closed without merging